<?php
    $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
    $product = $objectManager->get('Magento\Framework\Registry')->registry('current_product');//get current product
   // echo $product->getId();
   // echo $product->getTypeId(); //Main configurable product ID
    if ($product->getTypeId()=="simple") {
          $productCollection = $objectManager->create('Magento\Catalog\Model\Product')->load($product->getId());
          $productsplPrice = $productCollection->getSpecialPrice();
             if($productsplPrice){
    echo "<p style='color:red;'>SALE</p>";
   }
        
    }
  
?>

<div class="customclassrr"> </div>
<style type="text/css">
   .customclassrr{
   	color:red;
   	size:45px;
   }
</style>

